Specs
tb/northwind-graphql-ruby pull request #12
Opened 2017-10-16 20:00 UTC by dareddov

2017-10-17 09:14 UTC, stevo commented on spec/graphql/services/order_by_spec.rb
> +      it 'return a sorted by product_name list of 3 projects' do
descending

2017-10-17 09:15 UTC, stevo commented on spec/graphql/services/order_by_spec.rb
> +        expect(results).to match_array([third_product, second_product, first_product])
it does not assert order

2017-10-17 09:15 UTC, stevo commented on spec/graphql/services/order_by_spec.rb
> +
✂️

2017-10-17 09:21 UTC, stevo commented on spec/graphql/functions/update_spec.rb
> +        expect(updated_product.product_name).to eq 'New product name'
`product.reload`

2017-10-17 09:21 UTC, stevo commented on spec/graphql/functions/update_spec.rb
> +  describe '.call' do
`#call`

2017-10-17 09:22 UTC, stevo commented on spec/graphql/functions/find_by_id_spec.rb
> +end
line endings

2017-10-17 09:23 UTC, stevo commented on spec/graphql/functions/find_by_id_spec.rb
> +      it 'return product' do
`when provided id of exists product` -> `when id of existing product is provided`
`returns`

2017-10-17 09:23 UTC, stevo commented on spec/graphql/functions/find_by_id_spec.rb
> +        expect(found_product).not_to eq other_product
obsolete

2017-10-17 09:24 UTC, stevo commented on spec/graphql/functions/find_by_id_spec.rb
> +        found_product = Functions::FindById.new(Product).call(nil, params, nil)
`found_product` -> `result`

2017-10-17 09:25 UTC, stevo commented on spec/graphql/functions/find_all_spec.rb
> +      it 'return a list of products' do
all

2017-10-17 09:25 UTC, stevo commented on spec/graphql/functions/find_all_spec.rb
> +        products = create_list(:product, 5)
2

2017-10-17 09:26 UTC, stevo commented on spec/graphql/functions/find_all_spec.rb
> +    context 'when provided arguments have offset argument' do
`when offset is provided`

2017-10-17 09:27 UTC, stevo commented on spec/graphql/functions/find_all_spec.rb
> +      it 'return a list of products' do
records

2017-10-17 09:28 UTC, stevo commented on spec/graphql/functions/find_all_spec.rb
> +      it 'return a list of 3 products' do
`returns all records starting from offset provided`

2017-10-17 09:29 UTC, stevo commented on spec/graphql/functions/find_all_spec.rb
> +        products = create_list(:product, 5)
`product_1,  product_2,  product_3,  product_4 = create_list(:product, 4)`

2017-10-17 09:31 UTC, stevo commented on spec/graphql/functions/delete_spec.rb
> +        expect(product.persisted?).to be_falsey
`expect(Product.where(id: product.id)).to not_exist`

2017-10-17 09:32 UTC, stevo commented on spec/graphql/functions/delete_spec.rb
> +  context 'when provided product does not exists' do
`when record with id provided does not exist`

2017-10-17 09:32 UTC, stevo commented on spec/graphql/functions/create_spec.rb
> +      it 'not creates a product' do
`does not`

2017-10-17 09:33 UTC, stevo commented on spec/graphql/functions/create_spec.rb
> +    context 'when only require parameters are provided' do
`when valid parameters are provided`

2017-10-17 09:34 UTC, stevo commented on spec/graphql/functions/create_spec.rb
> +      it 'creates a product with a nested supplier' do
separate case

2017-10-17 09:36 UTC, stevo commented on app/graphql/services/nested_attributes.rb
> +    nested_keys.each { |key| attributes["#{key}_attributes"] = attributes.delete(key) }
consider using `transform_keys`

2017-10-17 09:41 UTC, stevo commented
https://github.com/Selleo/rspec-controller-matchers/blob/master/spec/support/controller_specs_boilerplate.rb
https://github.com/Selleo/rspec-controller-matchers/blob/master/spec/schema.rb

2017-10-17 16:38 UTC, tb commented on Gemfile
> +  gem 'factory_girl_rails'
we use it for seeds so its in global scope, do we need it twice?

2017-10-17 16:44 UTC, tb requested changes

2017-10-17 16:44 UTC, tb commented on spec/graphql/functions/create_spec.rb
> +                    'notes' => 'Something note'
In line 57+ we have `product_code: '6393283882',` etc. Cant we define fields/values once and use it here with stringify keys and without it in expect. After all it should be the same.

This applies to all those tests.

2017-12-27 20:52 UTC, johnunclesam commented on app/graphql/functions/create.rb
> +  private
Why `private attr_reader` ?

2018-02-11 20:22 UTC, closed without merging